### ISSUE TITLE
No podspec found for pusher_client_fixed

### ISSUE THREAD

**Issue by Skmlnv** [AbdoPrDZ/pusher_client_fixed#1]
No podspec found for `pusher_client_fixed` in `.symlinks/plugins/pusher_client_fixed/ios`, while running application on iOS. Android is working fine.

I cleared the build folders, did the pod integration again etc, but no luck, always this error during pod install.

version: 0.0.2

**Comment by AbdoPrDZ** [comment]
Hi, I'm so sorry, I only fixed the package for Android,
because i have never worked for ios and i can't do it because i don't have an ios phone or mac os
I'll think about it, maybe work with someone and fix it
so i'm sorry

**Comment by dragosholban** [comment]
Hi! I fixed the iOS part, I added a PR.

**Comment by AbdoPrDZ** [comment]
> Hi! I fixed the iOS part, I added a PR.

Thank you very much for fixing the problem. I will merge it soon

**Comment by AbdoPrDZ** [comment]
@everyone

Hey, there
i create this package that works on all platforms

[pusher_client_socket](https://pub.dev/packages/pusher_client_socket)

Please i need everyone to try it and let me know if you face any problem with it so I can improve it.
