### ISSUE TITLE
iOS Build Failed

### ISSUE THREAD

**Issue by malikdoksoz** [AbdoPrDZ/pusher_client_fixed#6]
Launching lib/main.dart on iPhone 15 in debug mode...
Xcode build done.                                           10,2s
Failed to build iOS app
Error (Xcode): Building for 'iOS-simulator', but linking in object file (/Users/mlkdksz/allfiles/files/apps/laravelechotest/ios/Pods/Sodium/Sodium/libsodium/libsodium-ios.a[arm64][3](libsodium_la-aead_xchacha20poly1305.o)) built for 'iOS'

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 15.

pusher_client_fixed: 0.0.3
flutter: 3.19
PC: Macbook M1 Pro

**Comment by AbdoPrDZ** [comment]
@everyone

Hey, there
i create this package that works on all platforms

[pusher_client_socket](https://pub.dev/packages/pusher_client_socket)

Please i need everyone to try it and let me know if you face any problem with it so I can improve it.

**Comment by malikdoksoz** [comment]
> @everyone
> 
> Hey, there i create this package that works on all platforms
> 
> [pusher_client_socket](https://pub.dev/packages/pusher_client_socket)
> 
> Please i need everyone to try it and let me know if you face any problem with it so I can improve it.

good job. i will try.
