### ISSUE TITLE
Support laravel reverb

### ISSUE THREAD

**Issue by karim-mesghouni** [AbdoPrDZ/pusher_client_fixed#8]
Add support for laravel reverb

**Comment by AbdoPrDZ** [comment]
hey, there
i create this package that works on all platforms

[pusher_client_socket](https://pub.dev/packages/pusher_client_socket)

i tried it with `Laravel/Reverb` its works there is example on README file to how connect it with `Laravel/Reverb`

**Comment by AbdoPrDZ** [comment]
hey, there
i create this package that works on all platforms

[pusher_client_socket](https://pub.dev/packages/pusher_client_socket)

i tried it with `Laravel/Reverb` its works there is example on README file to how connect it with `Laravel/Reverb`
